import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.recipes.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Brew</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user.isSignedIn ? (
        <>
          <SignOutButton className="btn-secondary btn" />
          <div
            className="hero min-h-screen"
            style={{
              backgroundImage: `url("/images/claude-piche-EHbtjmz7hvw-unsplash.jpg")`,
            }}
          >
            <div className="hero-overlay bg-opacity-60"></div>
            <div className="hero-content text-center text-neutral-content">
              <div className="max-w-md">
                <h1 className="mb-5 text-5xl font-bold">Brew!</h1>
                {data?.map((recipe) => (
                  <div key={recipe.id}>
                    <h2 className="text-center text-3xl font-bold text-primary">
                      {recipe.title}
                    </h2>
                    <pre className="whitespace-pre-wrap rounded-lg bg-base-100 p-1 text-left text-neutral">
                      {JSON.stringify(recipe.content, null, 2)}
                    </pre>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </>
      ) : (
        <div
          className="hero min-h-screen"
          style={{
            backgroundImage: `url("/images/claude-piche-EHbtjmz7hvw-unsplash.jpg")`,
          }}
        >
          <div className="hero-overlay bg-opacity-60"></div>
          <div className="hero-content text-center text-neutral-content">
            <div className="max-w-md">
              <h1 className="mb-5 text-5xl font-bold">Brew!</h1>
              <SignInButton className="btn-primary btn" />
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default Home;
